"""rename address

Revision ID: 545ca9ef027e
Revises: f1390aa46817
Create Date: 2024-10-01 23:39:40.074396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545ca9ef027e'
down_revision = 'f1390aa46817'
branch_labels = None
depends_on = None

#RENAMING COLUMNS
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
