"""rename department

Revision ID: f1390aa46817
Revises: 1cda4efd42cb
Create Date: 2024-10-01 23:30:06.096959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1390aa46817'
down_revision = '1cda4efd42cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('departments', 'department')
    # ### end Alembic commands ###
